// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxjvmrvbysnaonyosssn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4anZtcnZieXNuYW9ueW9zc3NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTYzNTYsImV4cCI6MjA3MzM3MjM1Nn0.Vb44JnIifd-PVJQjmGsTdsqwL3OCwLQgrEXMhUf6t3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});